http:
  port: 19200
  log:
    directory: /sent-messages

centralService:
  url: http://localhost:1042
  endpoints:
    stations: /stations.json

nats:
  url: nats://localhost:4222
  topics:
    warningMessageReceived: warningMessage.received.sender-service
    warningMessageSent: warningMessage.sent.sender-service

temporal:
  address: localhost:7233
  namespace: default