
http:
  port: 19200
  log:
    directory: /sent-messages

centralService:
  url: http://localhost:1042
  endpoints:
    stations: /stations.json

nats:
  url: nats://localhost:4222

temporal:
  address: localhost:7233
  namespace: default